# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RuffTech
email: l.c.ruff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog and projects by Lucas Ruff.
  A whole lot of nothing right now... room to grow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ruffte.ch" # the base hostname & protocol for your site
twitter_username: RuffLucas
github_username:  LucasRuff
linkedin_username: lucas-ruff-91516339

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
